services:
  - type: web
    name: todo-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DB_HOST
        value: 50.6.153.0
      - key: DB_USER
        value: asplcemy_Us_Latifa
      - key: DB_PASSWORD
        sync: false
        value: Latifa@2324
      - key: DB_NAME
        value: asplcemy_Latifa
